server {
    listen 80;
    server_name _;
    root /var/www/scholar-mm-production-v1;
    index index.html ai4talent-index-v29.html;

    location /assets/ {
        expires 30d;
        add_header Cache-Control "public";
    }

    location /data/ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/css application/javascript application/json application/octet-stream;
    gzip_min_length 1024;
}
